/* ═════════════════════════════════════════════════════════════════════════════
   THE SIX KNOCKOUT QUESTIONS

   Every screen — on WhatsApp, on the careers site or on the phone — asks the
   same six things, because they are the six that decide whether a recruiter's
   half hour is worth spending: where they are, whether they may work here, when
   they could start, what they cost, what language they sell in, and how long
   they have been doing it.

   The wording is built from the requisition, so the candidate is asked about
   *this* job's city, family and band rather than about hiring in the abstract.
   The scoring is out of two each, twelve in total, which is what the 1–100 on
   the drawer is a percentage of.

   Nothing here is generated by a model. A question is a sentence assembled from
   the record, and a score is a rule applied to what the candidate actually
   said — both of which a recruiter can check and argue with.
   ═════════════════════════════════════════════════════════════════════════════*/

export type ScreenKey =
  | 'location' | 'right_to_work' | 'notice' | 'salary' | 'arabic' | 'experience';

export type ScreenQuestion = { key: ScreenKey; question: string; max: number };

export type QuestionContext = {
  jobTitle: string;
  family: string;
  city: string;
  remoteOk: boolean;
  salaryMin: number | null;
  salaryMax: number | null;
};

const sar = (n: number | null) =>
  n == null ? '—' : `SAR ${n.toLocaleString('en-US')}`;

export function screenQuestions(c: QuestionContext): ScreenQuestion[] {
  return [
    {
      key: 'location',
      question: `Are you currently based in ${c.city}, or open to relocating there?`,
      max: 2,
    },
    {
      key: 'right_to_work',
      question: 'Do you hold a transferable iqama or the right to work in Saudi Arabia?',
      max: 2,
    },
    {
      key: 'notice',
      question: 'What is your notice period with your current employer?',
      max: 2,
    },
    {
      key: 'salary',
      question: `The band for this role is ${sar(c.salaryMin)} to ${sar(c.salaryMax)} monthly. `
        + 'What are you on today, and what are you expecting?',
      max: 2,
    },
    {
      key: 'arabic',
      question: 'How would you rate your spoken Arabic?',
      max: 2,
    },
    {
      key: 'experience',
      question: `How many years have you worked in ${c.family.toLowerCase()} roles?`,
      max: 2,
    },
  ];
}

/* ── Reading an answer ──────────────────────────────────────────────────────*/

const YES = /\b(yes|yeah|yep|na['’]am|نعم|i am|i do|i have|correct|of course)\b/i;
const NO = /\b(no|not|nope|la|لا|don['’]?t|do not|cannot|can['’]?t)\b/i;

/** Every SAR figure in a sentence, in the order they were said. */
export function moneyIn(text: string): number[] {
  const out: number[] = [];
  /* A monthly salary in this market is between two thousand and two hundred
     thousand riyals. Anything outside that is a date, a phone number or a
     house number, and reading it as pay is worse than reading nothing. */
  const push = (n: number) => {
    if (Number.isFinite(n) && n >= 2000 && n <= 200_000 && !out.includes(n)) out.push(n);
  };
  let m: RegExpExecArray | null;

  /* With the currency on it, either side: "SAR 18,000", "18000 SAR",
     "18000 a month". */
  const withCurrency = /(?:sar|ر\.?س|riyals?)\s*([\d][\d,\s.]{2,11})|([\d][\d,]{3,8})\s*(?:sar|riyals?|a month|monthly|per month)/gi;
  while ((m = withCurrency.exec(text))) {
    push(Number((m[1] ?? m[2] ?? '').replace(/[^\d]/g, '')));
  }

  /* A range in thousands, where only the second number carries the k:
     "16-20k", "16 to 20k". Both ends are the answer. */
  const thousandRange = /(\d{1,3}(?:[.,]\d)?)\s*(?:-|–|to|and)\s*(\d{1,3}(?:[.,]\d)?)\s*k\b/gi;
  while ((m = thousandRange.exec(text))) {
    push(Math.round(Number(m[1].replace(',', '.')) * 1000));
    push(Math.round(Number(m[2].replace(',', '.')) * 1000));
  }

  /* In thousands, which is how most people actually answer: "18k", "18.5k".
     The k is what marks it as money, so it needs no currency beside it — and a
     screen that read "18k" as no answer scored it a one and moved the verdict,
     which is the bug this catches. */
  const inThousands = /(\d{1,3}(?:[.,]\d)?)\s*k\b/gi;
  while ((m = inThousands.exec(text))) {
    push(Math.round(Number(m[1].replace(',', '.')) * 1000));
  }

  /* A bare five-figure number, alone or in a range: "18000", "16000 to
     20000". Four figures and under are left alone — "2 500" is as likely to
     be a date as a wage, and the two forms above already catch every way
     somebody says they mean money. */
  const bare = /(?<![\d.,])(\d{2},?\d{3})(?![\d.,])/g;
  while ((m = bare.exec(text))) {
    push(Number(m[1].replace(/[^\d]/g, '')));
  }

  return out.sort((a, b) => a - b);
}

/* Spelled out rather than typed as a figure, which is how a person answers a
   question about their notice: "one month", "a couple of weeks". */
const WORD_NUMBERS: Record<string, number> = {
  a: 1, an: 1, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6,
  seven: 7, eight: 8, nine: 9, ten: 10, fourteen: 14, thirty: 30,
};

/** The first number of days, weeks or months an answer mentions. */
export function noticeIn(text: string): number | null {
  const immediate = /\b(immediate|immediately|right away|available now|no notice|serving)\b/i;
  const word = (w: string): number | null =>
    (/^\d/.test(w) ? Number(w) : WORD_NUMBERS[w.toLowerCase()] ?? null);

  const months = text.match(/(\d{1,2})\s*month/i)
    ?? text.match(/\b(a|an|one|two|three|four|five|six)\s+months?\b/i);
  if (months) { const n = word(months[1]); if (n != null) return n * 30; }

  const days = text.match(/(\d{1,3})\s*(?:day|يوم)/i)
    ?? text.match(/\b(a|an|one|two|three|seven|ten|fourteen|thirty)\s+days?\b/i);
  if (days) { const n = word(days[1]); if (n != null) return n; }

  const weeks = text.match(/(\d{1,2})\s*week/i)
    ?? text.match(/\b(a|an|one|two|three|four|six)\s+weeks?\b/i);
  if (weeks) { const n = word(weeks[1]); if (n != null) return n * 7; }

  if (immediate.test(text)) return 0;
  return null;
}

export function yearsIn(text: string): number | null {
  const m = text.match(/(\d{1,2})(?:\.\d)?\s*(?:\+)?\s*(?:year|yr|سنة|سنوات)/i);
  if (m) return Number(m[1]);
  const bare = text.match(/^\s*(\d{1,2})\s*$/);
  return bare ? Number(bare[1]) : null;
}

export type ArabicLevel = 'Native' | 'Fluent' | 'Conversational' | 'Basic' | 'None';

export function arabicIn(text: string): ArabicLevel | null {
  const t = text.toLowerCase();
  if (/\bnative|mother tongue|first language\b/.test(t)) return 'Native';
  if (/\bfluent|bilingual\b/.test(t)) return 'Fluent';
  if (/\bconversational|good|comfortable|business\b/.test(t)) return 'Conversational';
  /* "A few words" and "I get by" are how somebody says basic without saying
     basic, and those are the answers that actually arrive. */
  if (/\bbasic|little|some|beginner|understand more|few words|get by|not much\b/.test(t)) return 'Basic';
  if (/\bnone|no arabic|don['’]?t speak|do not speak\b/.test(t)) return 'None';
  return null;
}

export type ScoreContext = QuestionContext & {
  /** The families where Arabic is customer-facing, so a weaker level costs more. */
  arabicMatters: boolean;
  /** The years this requisition really wants — five on a senior band, two below. */
  wantsYears: number;
};

/** What a requisition is worth on the Arabic question depends on the family. */
export const ARABIC_FAMILIES = ['Sales', 'Integrated Services', 'Operations'];

/**
 * Score one answer out of two. A blank answer scores nothing rather than
 * defaulting to the middle: an unanswered knockout is a knockout.
 */
export function scoreAnswer(key: ScreenKey, answer: string, c: ScoreContext): number {
  const a = (answer ?? '').trim();
  if (!a) return 0;

  switch (key) {
    case 'location': {
      const here = new RegExp(`\\b${c.city}\\b`, 'i').test(a) && !/\brelocat|move\b/i.test(a);
      if (here) return 2;
      if (c.remoteOk) return 2;
      if (/\brelocat|move|happy to|willing\b/i.test(a)) return 1;
      return NO.test(a) ? 0 : 1;
    }

    case 'right_to_work': {
      if (/\bsaudi national|citizen|transferable|iqama|right to work\b/i.test(a) && !NO.test(a)) return 2;
      if (YES.test(a)) return 2;
      if (/\bsponsor|visa needed|not transferable\b/i.test(a)) return 0;
      return NO.test(a) ? 0 : 1;
    }

    case 'notice': {
      const days = noticeIn(a);
      if (days === null) return 1;
      return days <= 30 ? 2 : days <= 60 ? 1 : 0;
    }

    case 'salary': {
      const nums = moneyIn(a);
      if (!nums.length || c.salaryMax == null) return 1;
      const asking = Math.max(...nums);
      if (asking <= c.salaryMax) return 2;
      return asking <= c.salaryMax * 1.15 ? 1 : 0;
    }

    case 'arabic': {
      const level = arabicIn(a);
      if (level === 'Native' || level === 'Fluent') return 2;
      if (level === 'Conversational') return c.arabicMatters ? 1 : 2;
      if (level === 'Basic') return c.arabicMatters ? 0 : 1;
      if (level === 'None') return c.arabicMatters ? 0 : 1;
      return 1;
    }

    case 'experience': {
      const years = yearsIn(a);
      if (years === null) return /\bgraduate|fresh|no experience\b/i.test(a) ? 0 : 1;
      return years >= c.wantsYears ? 2 : years >= 1 ? 1 : 0;
    }

    default:
      return 0;
  }
}

/** Pass, review or regret — the line the drawer and the board read. */
export function verdictOf(total: number, max: number): 'pass' | 'review' | 'fail' {
  if (!max) return 'review';
  const pct = (total / max) * 100;
  return pct >= 75 ? 'pass' : pct >= 50 ? 'review' : 'fail';
}

/** The sentence under the score, written from the weak answers. */
export function summaryOf(
  verdict: 'pass' | 'review' | 'fail',
  weak: string[],
): string {
  const readable = weak.map((k) => k.replace(/_/g, ' '));
  const list = readable.length > 1
    ? `${readable.slice(0, -1).join(', ')} and ${readable[readable.length - 1]}`
    : readable[0];
  if (verdict === 'pass') return 'Clears every knockout. Ready for a recruiter screen.';
  if (verdict === 'review') return `Worth a call — check ${list ?? 'the weaker answers'} first.`;
  return `Misses on ${list ?? 'the knockouts'}. Recommend a polite regret unless the requisition changes.`;
}
